'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { projectsApi } from '@/lib/api/projects';
import { reportsApi } from '@/lib/api/reports';
import { sprintsApi } from '@/lib/api/sprints';
import type { ItemType } from '@/lib/types';
import styles from './reports.module.css';

const Group = ({ title, rows }: { title: string; rows: Array<{ label: string; count: number }> }) => <section className={styles.card}><h2>{title}</h2>{rows.length ? rows.map((row) => <div className={styles.row} key={row.label}><span>{row.label}</span><strong>{row.count}</strong></div>) : <p>Nenhum dado.</p>}</section>;

export default function ReportsPage() {
  const [projectOverride, setProjectOverride] = useState(''); const [type, setType] = useState<ItemType | ''>(''); const [sprintId, setSprintId] = useState(''); const [exporting, setExporting] = useState(''); const [error, setError] = useState('');
  const projectsQuery = useQuery({ queryKey: ['projects'], queryFn: projectsApi.list }); const projects = projectsQuery.data || []; const projectId = projects.some((project) => project.id === projectOverride) ? projectOverride : projects[0]?.id || '';
  const sprintsQuery = useQuery({ queryKey: ['report-sprints', projectId], queryFn: () => sprintsApi.list(projectId), enabled: Boolean(projectId) });
  const filters = { project_id: projectId, ...(type ? { type } : {}), ...(sprintId ? { sprint_id: sprintId } : {}) };
  const reportQuery = useQuery({ queryKey: ['operational-report', filters], queryFn: () => reportsApi.operational(filters), enabled: Boolean(projectId) });
  const download = async (target: 'items' | 'backlog' | 'sprint' | 'bugs') => { setError(''); setExporting(target); try { await reportsApi.download(target, filters); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao exportar'); } finally { setExporting(''); } };
  return <div><header className={styles.header}><div><h1>Relatórios operacionais</h1><p>Indicadores e exportações do projeto com os filtros aplicados.</p></div></header>
    <div className={styles.filters}><select value={projectId} onChange={(event) => { setProjectOverride(event.target.value); setSprintId(''); }}><option value="">Selecione o projeto</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select value={type} onChange={(event) => setType(event.target.value as ItemType | '')}><option value="">Todos os tipos</option>{['EPIC','STORY','TASK','SUBTASK','BUG'].map((value) => <option key={value}>{value}</option>)}</select><select value={sprintId} onChange={(event) => setSprintId(event.target.value)}><option value="">Todas as sprints</option>{sprintsQuery.data?.map((sprint) => <option key={sprint.id} value={sprint.id}>{sprint.name}</option>)}</select></div>
    <div className={styles.exports}>{(['items','backlog','sprint','bugs'] as const).map((target) => <button key={target} disabled={Boolean(exporting) || (target === 'sprint' && !sprintId)} onClick={() => download(target)}>Exportar {target} CSV{exporting === target ? '…' : ''}</button>)}</div>{error && <p className={styles.error}>{error}</p>}
    {projectsQuery.isLoading || reportQuery.isLoading ? <div className={styles.state}>Carregando relatórios…</div> : projectsQuery.isError || reportQuery.isError ? <div className={styles.error}>Não foi possível carregar os relatórios.</div> : !reportQuery.data ? <div className={styles.state}>Selecione um projeto.</div> : <><div className={styles.grid}><Group title="Itens por status" rows={reportQuery.data.itemsByStatus} /><Group title="Itens por responsável" rows={reportQuery.data.itemsByAssignee} /><Group title="Bugs por severidade" rows={reportQuery.data.bugsBySeverity} /><Group title="Bugs por ambiente" rows={reportQuery.data.bugsByEnvironment} /><Group title="Bugs por responsável" rows={reportQuery.data.bugsByAssignee} /><section className={styles.card}><h2>Indicadores de bugs</h2><div className={styles.row}><span>Reabertos</span><strong>{reportQuery.data.reopenedBugs}</strong></div><div className={styles.row}><span>Tempo médio em aberto</span><strong>{reportQuery.data.averageOpenDays} dias</strong></div></section></div><section className={styles.card}><h2>Progresso por épico</h2>{reportQuery.data.epicProgress.length ? reportQuery.data.epicProgress.map((epic) => <div className={styles.epic} key={epic.id}><span>{epic.key} · {epic.title}</span><progress max="100" value={epic.percentage}/><strong>{epic.percentage}%</strong></div>) : <p>Nenhum épico.</p>}</section><section className={styles.card}><h2>Resultado da sprint</h2>{reportQuery.data.sprintResult ? <div className={styles.row}><span>{reportQuery.data.sprintResult.name}</span><strong>{reportQuery.data.sprintResult.completedPoints} / {reportQuery.data.sprintResult.plannedPoints} pontos</strong></div> : <p>Nenhuma sprint encontrada.</p>}</section><p className={styles.generated}>Atualizado em {new Date(reportQuery.data.generatedAt).toLocaleString('pt-BR')}</p></>}
  </div>;
}
