-- AlterTable
ALTER TABLE `item_history` MODIFY `event_type` ENUM('ITEM_CREATED', 'TITLE_CHANGED', 'DESCRIPTION_CHANGED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'ASSIGNEE_CHANGED', 'SPRINT_CHANGED', 'ESTIMATE_CHANGED', 'ACCEPTANCE_CRITERIA_CHANGED', 'COMMENT_CREATED', 'COMMENT_EDITED', 'COMMENT_DELETED', 'ATTACHMENT_UPLOADED', 'ATTACHMENT_DOWNLOADED', 'ATTACHMENT_DELETED', 'WATCHER_ADDED', 'WATCHER_REMOVED', 'BUG_RETEST_RECORDED', 'BUG_REOPENED') NOT NULL;

-- CreateTable
CREATE TABLE `bug_retests` (
  `id` VARCHAR(191) NOT NULL,
  `bug_id` VARCHAR(191) NOT NULL,
  `tester_id` VARCHAR(191) NOT NULL,
  `environment` ENUM('DEVELOPMENT', 'TEST', 'HOMOLOGATION', 'PRODUCTION') NOT NULL,
  `result` ENUM('APPROVED', 'FAILED', 'BLOCKED', 'NOT_TESTED') NOT NULL,
  `observations` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  INDEX `bug_retests_bug_id_createdAt_idx`(`bug_id`, `createdAt`),
  INDEX `bug_retests_tester_id_idx`(`tester_id`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `bug_retests` ADD CONSTRAINT `bug_retests_bug_id_fkey` FOREIGN KEY (`bug_id`) REFERENCES `items`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `bug_retests` ADD CONSTRAINT `bug_retests_tester_id_fkey` FOREIGN KEY (`tester_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
