'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { WEBHOOK_EVENTS, webhooksApi } from '@/lib/api/webhooks';
import styles from './webhookSettings.module.css';
export default function WebhookSettings({projectId,canManage}:{projectId:string;canManage:boolean}){
 const client=useQueryClient(); const [form,setForm]=useState({name:'',url:'',events:['ITEM_CREATED'] as string[]}); const [secret,setSecret]=useState(''); const [notice,setNotice]=useState(''); const key=['project-webhooks',projectId]; const deliveriesKey=['webhook-deliveries',projectId];
 const webhooks=useQuery({queryKey:key,queryFn:()=>webhooksApi.list(projectId),enabled:canManage}); const deliveries=useQuery({queryKey:deliveriesKey,queryFn:()=>webhooksApi.deliveries(projectId),enabled:canManage,refetchInterval:5000});
 const refresh=()=>{client.invalidateQueries({queryKey:key});client.invalidateQueries({queryKey:deliveriesKey});};
 const create=useMutation({mutationFn:()=>webhooksApi.create(projectId,form),onSuccess:(value)=>{setSecret(value.secret||'');setForm({name:'',url:'',events:['ITEM_CREATED']});refresh();}});
 const action=useMutation({mutationFn:({kind,id,active}:{kind:'test'|'retry'|'toggle';id:string;active?:boolean})=>kind==='test'?webhooksApi.test(projectId,id):kind==='retry'?webhooksApi.retry(projectId,id):webhooksApi.update(projectId,id,{is_active:active}),onSuccess:(_,variables)=>{setNotice(variables.kind==='test'?'Evento webhook.test enfileirado. Acompanhe a entrega abaixo.':variables.kind==='retry'?'Entrega enfileirada novamente.':'Webhook atualizado.');refresh();}});
 if(!canManage)return null; return <section className={styles.panel}><h2>Webhooks</h2><p>Entregas assinadas são processadas fora da requisição principal. O evento de teste é compatível com o Webhook node do n8n.</p>{notice&&<p className={styles.notice}>{notice}</p>}{secret&&<div className={styles.secret}><strong>Copie o segredo agora — ele não será exibido novamente.</strong><code>{secret}</code><button onClick={()=>setSecret('')}>Ocultar</button></div>}
 <form onSubmit={(e)=>{e.preventDefault();create.mutate();}} className={styles.form}><input placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="url" placeholder="https://webhook.exemplo.com/eventos" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><div className={styles.events}>{WEBHOOK_EVENTS.map(event=><label key={event}><input type="checkbox" checked={form.events.includes(event)} onChange={()=>setForm({...form,events:form.events.includes(event)?form.events.filter(value=>value!==event):[...form.events,event]})}/>{event}</label>)}</div><button disabled={create.isPending||!form.name||!form.url||!form.events.length}>Criar webhook</button></form>{create.error&&<p className={styles.error}>{create.error.message}</p>}
 {webhooks.isLoading?<p>Carregando…</p>:webhooks.isError?<p className={styles.error}>Falha ao carregar webhooks.</p>:webhooks.data?.length?<div className={styles.list}>{webhooks.data.map(hook=><div key={hook.id} className={styles.hook}><div><strong>{hook.name}</strong><code>{hook.url}</code><small>{hook.events.join(', ')} · {hook._count?.deliveries||0} entregas</small></div><button onClick={()=>action.mutate({kind:'test',id:hook.id})}>Testar</button><button onClick={()=>action.mutate({kind:'toggle',id:hook.id,active:!hook.is_active})}>{hook.is_active?'Desativar':'Ativar'}</button></div>)}</div>:<p>Nenhum webhook configurado.</p>}
 <details className={styles.docs}><summary>Formato enviado ao n8n</summary><pre>{`{"eventId":"uuid","event":"bug.created","version":1,"occurredAt":"ISO-8601","actor":{"id":"user-id"},"project":{"id":"project-id"},"entity":{"type":"bug","id":"item-id"},"item":{"id":"item-id","key":"MINI-42"},"data":{}}`}</pre><p>Valide o header X-MiniAgil-Signature com HMAC-SHA256 sobre o corpo bruto.</p></details><h3>Entregas recentes</h3>{deliveries.isLoading?<p>Carregando entregas…</p>:deliveries.data?.length?<div className={styles.deliveries}>{deliveries.data.map(item=><div key={item.id}><span><strong>{item.webhook.name}</strong> · {item.event_type}</span><span>{item.status} · {item.attempt_count} tentativa(s){item.response_status?` · HTTP ${item.response_status}`:''}</span>{item.last_error&&<small>{item.last_error}</small>}{item.status==='FAILED'&&<button onClick={()=>action.mutate({kind:'retry',id:item.id})}>Reprocessar</button>}</div>)}</div>:<p>Nenhuma entrega registrada.</p>}</section>;
}
