export const queryKeys = {
  auth: ['auth'] as const,
  me: ['auth', 'me'] as const,
  projects: ['projects'] as const,
  project: (id: string) => ['projects', id] as const,
  projectWorkflows: (id: string) => ['projects', id, 'workflows'] as const,
  projectWorkflow: (id: string, type: string) => ['projects', id, 'workflows', type] as const,
  customFields: (id: string, type: string, inactive = false) => ['projects', id, 'custom-fields', type, inactive] as const,
  savedViews: (id: string) => ['projects', id, 'saved-views'] as const,
  items: ['items'] as const,
  itemsByFilter: (filterKey: string) => ['items', filterKey] as const,
  itemStatuses: (projectId?: string, type?: string) => ['items', 'statuses', projectId || 'legacy', type || 'all'] as const,
  itemComments: (itemId: string) => ['items', itemId, 'comments'] as const,
  itemHistory: (itemId: string) => ['items', itemId, 'history'] as const,
  itemAttachments: (itemId: string) => ['items', itemId, 'attachments'] as const,
  bugRetests: (itemId: string) => ['items', itemId, 'retests'] as const,
  hierarchicalItems: (projectId: string) => ['items', 'hierarchical', projectId] as const,
  hierarchicalTree: ['items', 'hierarchical-tree'] as const,
  dashboardMetrics: ['items', 'dashboard-metrics'] as const,
  backlogOverview: (projectId: string, filtersKey = '') => ['items', 'backlog-overview', projectId, filtersKey] as const,
  sprints: (projectId: string) => ['sprints', projectId] as const,
  users: ['users'] as const,
  teams: ['teams'] as const,
};

