-- AlterTable
ALTER TABLE `item_history` MODIFY `event_type` ENUM('ITEM_CREATED', 'TITLE_CHANGED', 'DESCRIPTION_CHANGED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'ASSIGNEE_CHANGED', 'SPRINT_CHANGED', 'ESTIMATE_CHANGED', 'ACCEPTANCE_CRITERIA_CHANGED', 'COMMENT_CREATED', 'COMMENT_EDITED', 'COMMENT_DELETED', 'ATTACHMENT_UPLOADED', 'ATTACHMENT_DOWNLOADED', 'ATTACHMENT_DELETED') NOT NULL;
