-- AlterEnumAndTable
ALTER TABLE `bugs`
    MODIFY `status` ENUM('OPEN', 'TRIAGE', 'IN_PROGRESS', 'CONFIRMED', 'IN_FIX', 'WAITING_VALIDATION', 'RESOLVED', 'CLOSED', 'REOPENED', 'REJECTED', 'DUPLICATED', 'CANCELED') NOT NULL DEFAULT 'OPEN',
    ADD COLUMN `resolvedAt` DATETIME(3) NULL,
    ADD COLUMN `closedAt` DATETIME(3) NULL;

ALTER TABLE `bug_status_history`
    MODIFY `from_status` ENUM('OPEN', 'TRIAGE', 'IN_PROGRESS', 'CONFIRMED', 'IN_FIX', 'WAITING_VALIDATION', 'RESOLVED', 'CLOSED', 'REOPENED', 'REJECTED', 'DUPLICATED', 'CANCELED') NULL,
    MODIFY `to_status` ENUM('OPEN', 'TRIAGE', 'IN_PROGRESS', 'CONFIRMED', 'IN_FIX', 'WAITING_VALIDATION', 'RESOLVED', 'CLOSED', 'REOPENED', 'REJECTED', 'DUPLICATED', 'CANCELED') NOT NULL,
    ADD COLUMN `comment` TEXT NULL;

UPDATE `bugs` SET `status` = 'IN_FIX' WHERE `status` = 'IN_PROGRESS';
UPDATE `bug_status_history` SET `from_status` = 'IN_FIX' WHERE `from_status` = 'IN_PROGRESS';
UPDATE `bug_status_history` SET `to_status` = 'IN_FIX' WHERE `to_status` = 'IN_PROGRESS';
UPDATE `bugs` SET `resolvedAt` = `updatedAt` WHERE `status` = 'RESOLVED' AND `resolvedAt` IS NULL;
UPDATE `bugs` SET `closedAt` = `updatedAt` WHERE `status` = 'CLOSED' AND `closedAt` IS NULL;

ALTER TABLE `bugs`
    MODIFY `status` ENUM('OPEN', 'TRIAGE', 'CONFIRMED', 'IN_FIX', 'WAITING_VALIDATION', 'RESOLVED', 'CLOSED', 'REOPENED', 'REJECTED', 'DUPLICATED', 'CANCELED') NOT NULL DEFAULT 'OPEN';

ALTER TABLE `bug_status_history`
    MODIFY `from_status` ENUM('OPEN', 'TRIAGE', 'CONFIRMED', 'IN_FIX', 'WAITING_VALIDATION', 'RESOLVED', 'CLOSED', 'REOPENED', 'REJECTED', 'DUPLICATED', 'CANCELED') NULL,
    MODIFY `to_status` ENUM('OPEN', 'TRIAGE', 'CONFIRMED', 'IN_FIX', 'WAITING_VALIDATION', 'RESOLVED', 'CLOSED', 'REOPENED', 'REJECTED', 'DUPLICATED', 'CANCELED') NOT NULL;
